/** C-I01 — Stablecoin peg mechanics. Source: docs/lessons/CRYPTO_INTERMEDIATE.md §C-I01. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_C_I01: LessonContent = {
  id: "lesson:stablecoin-peg-mechanics",
  curriculumId: "C-I01",
  title: "Stablecoin Peg Mechanics",
  track: "crypto",
  pages: [
    [
      "HarborUSD is designed to trade 1:1 with a fictional",
      "reserve unit (USVC). In normal operation it holds",
      "within $0.998–$1.002. That narrow band is what makes",
      "it useful as a settlement layer. But stability is not",
      "guaranteed — it is a function of mechanism design, and",
      "mechanisms can fail.",
      "",
      "Stablecoins use two broad categories:",
      "• Collateral-backed: holds real assets as reserve.",
      "• Algorithmic: maintains peg through incentives &",
      "  market actors, not locked collateral.",
      "",
      "This lesson focuses on algorithmic stables because",
      "their failure mode teaches cascade logic.",
    ],
    [
      "How an algorithmic stable holds its peg:",
      "",
      "The system involves two tokens: the S-token (the stable)",
      "and the C-token (companion). When S-token trades below",
      "$1, arbitrageurs burn S-tokens to mint C-tokens at a",
      "favorable ratio. This reduces S-token supply and pushes",
      "price back up.",
      "",
      "When S-token trades above $1, the opposite occurs: burn",
      "C-tokens to mint S-tokens, increasing supply and pulling",
      "price back down.",
      "",
      "The peg holds as long as arbitrageurs trust the system",
      "and C-tokens have residual value.",
    ],
    [
      "The cascade anatomy: A depeg unfolds in phases.",
      "",
      "1. Initial sell pressure — large holder exits. S-token",
      "   price drops below $1.",
      "",
      "2. Arbitrage slows — if C-token is already falling, the",
      "   arbitrage incentive weakens.",
      "",
      "3. Confidence crack — other holders observe and begin",
      "   exiting. Exit demand exceeds buy-side depth.",
      "",
      "4. Liquidity cascade — C-token must absorb more minting",
      "   pressure. Self-reinforcing loop: C-token falls →",
      "   arbitrage becomes unprofitable → S-token falls further.",
      "",
      "5. Bid vacuum — order book thins. Price moves to nearly",
      "   zero because the structural buyer (arbitrage) broke.",
    ],
    [
      "Why this matters beyond stablecoins:",
      "",
      "The cascade logic (mechanism breaks → structural buyers",
      "disappear → price finds no floor) appears in:",
      "• Grid-bots accumulating one-sided exposure in a trend",
      "• Liquidity pools where the underlying pair is worthless",
      "• Leveraged positions where margin calls force selling",
      "  into thin order books",
      "",
      "Process note: If you hold any stability-mechanism",
      "instrument, the question is not 'is it stable?' (it has",
      "been until now). The question is: what is the mechanism,",
      "and what does it require to keep working? If you cannot",
      "answer that, you do not fully understand your risk.",
    ],
  ],
  processCheck:
    "Describe the sequence of events in a stablecoin depeg — confidence crack, arbitrage breakdown, bid vacuum — without referencing a specific real coin, in plain language, in under two minutes.",
  cta: { kind: "scenario", id: "SCN-001", line: "Practice this now: the HarborUSD depegging scenario." },
};
