/** C-I02 — Flash crash anatomy. Source: docs/lessons/CRYPTO_INTERMEDIATE.md §C-I02. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_C_I02: LessonContent = {
  id: "lesson:flash-crash-anatomy",
  curriculumId: "C-I02",
  title: "Flash Crash Anatomy",
  track: "crypto",
  pages: [
    [
      "A flash crash is a rapid, extreme price decline — often",
      "20–50% or more within minutes — followed by a partial or",
      "full recovery. The recovery can feel reassuring in",
      "retrospect, but the lesson is not \"price came back.\"",
      "The lesson is the sequence that made the drop possible",
      "and the one action that matters before it happens.",
      "",
      "Three conditions combine to produce a flash crash:",
      "",
      "1. Leveraged positions concentrated near the same stop",
      "   or liquidation level.",
      "2. Thin order books — depth varies by time of day.",
      "3. A triggering event — a large sell, news, or stop",
      "   cluster hit at a key level.",
    ],
    [
      "The cascade sequence:",
      "",
      "Once the trigger fires and the first liquidations hit,",
      "the sequence is largely mechanical:",
      "",
      "• Liquidated positions sell at market into whatever",
      "  bids exist.",
      "• Bids are exhausted; price moves to the next bid.",
      "• That movement triggers another cluster of liquidations.",
      "• The feedback loop continues until the liquidation",
      "  queue empties, new buyers step in, or price reaches",
      "  a level where bids are finally deep enough.",
    ],
    [
      "Worked example — GLIMMER at $100:",
      "",
      "Liquidation levels from leveraged longs cluster at $92,",
      "$88, and $84. The book has thin bids between those",
      "levels. A large market sell of 50,000 GLIMMER hits.",
      "",
      "Price drops to $93. Liquidations at $92 trigger: 80,000",
      "more GLIMMER hits the sell queue. Price gaps to $88.",
      "Liquidations at $88 trigger: 120,000 more. Price gaps",
      "to $81 — below the $84 cluster — because the book",
      "between $88 and $84 has almost no bids.",
      "",
      "At $81, institutional buyers step in. Price recovers to",
      "$91 over 20 minutes.",
    ],
    [
      "Unlevered vs. leveraged:",
      "",
      "An unlevered spot holder who bought at $100 experienced",
      "a drawdown to $81 (19%) and watched partial recovery to",
      "$91. They cannot be liquidated; loss is temporary unless",
      "they sell. A leveraged holder at 5× with a stop at $92",
      "was liquidated near $92 — loss crystallized; they did not",
      "participate in the recovery.",
      "",
      "The one action available before — not during:",
      "",
      "During a flash crash, there is functionally nothing you",
      "can do. The move happens in minutes. Before a volatile",
      "period, reduce position size to a level you can hold",
      "without a stop, or set your stop assuming a larger spike.",
    ],
  ],
  processCheck:
    "What is the one action you would take before a volatile period — not during — to reduce your exposure to a flash crash event?",
  cta: { kind: "scenario", id: "SCN-004", line: "Practice this now: GLIMMER volatility in the pool scenario." },
};
