/** S-I01 — Earnings seasons. Source: docs/lessons/STOCKS_INTERMEDIATE.md §S-I01. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_S_I01: LessonContent = {
  id: "lesson:earnings-seasons",
  curriculumId: "S-I01",
  title: "Earnings Seasons",
  track: "stocks",
  pages: [
    [
      "Four times a year, every publicly listed company reports",
      "its financial results for the past quarter. This is",
      "earnings season — a concentrated window where large",
      "numbers of companies release simultaneously and the",
      "market reprices many stocks quickly. For traders, it is",
      "a period of structural risk requiring explicit policy",
      "decisions before positions are opened or held.",
      "",
      "What is reported:",
      "• Revenue and earnings per share (EPS): actual numbers",
      "  for the quarter just ended.",
      "• Forward guidance: management's projection for the next",
      "  quarter or fiscal year — revenue range, margins,",
      "  operating metrics.",
      "",
      "The market prices stocks on expectations about the",
      "future, not just the past. A quarterly result is already",
      "in the past; the market reacts to whether it changes",
      "forward expectations.",
    ],
    [
      "Why a beat can gap down:",
      "",
      "NGSM reports $2.40 EPS. Analysts expected $2.20. That is",
      "a beat. But NGSM's guidance for next quarter is $2.10",
      "EPS, below the $2.30 analysts had projected. The stock",
      "gaps down because the market's forward expectation has",
      "been revised lower, despite the strong current result.",
      "",
      "Why a miss can gap up:",
      "",
      "VLDI reports $1.80 EPS. Analysts expected $2.05. That is",
      "a miss. But VLDI revises its full-year revenue guidance",
      "upward by 15% and announces a major new contract. The",
      "miss on one quarter does not change forward expectation;",
      "the guidance revision and contract raise it. Price gaps",
      "up despite the miss.",
    ],
    [
      "The pre-event sizing decision:",
      "",
      "Three valid policy choices when an earnings event",
      "approaches:",
      "",
      "1. Exit before the report. Crystallize your gain or loss",
      "   before the binary event. Eliminate earnings gap risk",
      "   entirely. Also eliminate possibility of favorable gap.",
      "",
      "2. Hold with a sized position. Reduce position to a size",
      "   where even a gap to your maximum acceptable loss does",
      "   not exceed your account risk limit (covered in F-03).",
      "",
      "3. Observe and re-enter after the open. Let the gap",
      "   occur; trade the reaction after the market has had",
      "   20–30 minutes to process. Covered in S-I02.",
      "",
      "None is universally correct. The process requirement:",
      "one of them is chosen and written down before the",
      "earnings date arrives.",
    ],
    [
      "Worked example:",
      "",
      "NGSM is at $120 ahead of earnings. You hold 50 shares",
      "($6,000 position). Your stop is at $115. After close,",
      "NGSM reports strong quarter but soft guidance. The stock",
      "opens next day at $104 — a gap of $16 per share, below",
      "your $115 stop.",
      "",
      "Your stop-market order was live at $115. But price never",
      "traded there. It opened at $104. Your stop triggered at",
      "market open and filled at ~$104. Loss: $16 × 50 = $800,",
      "not the $250 your stop was designed to limit.",
      "",
      "This lesson is not about whether to hold through",
      "earnings. It is about knowing your exposure before the",
      "event, so the outcome — whatever it is — was a",
      "considered choice, not a surprise.",
    ],
  ],
  processCheck:
    "Do you know your earnings exposure — position size, maximum acceptable gap loss, and stated policy — before the earnings date arrives, not at the market open?",
  cta: { kind: "scenario", id: "SCN-005", line: "Practice this now: the earnings season scenario." },
};
