/** S-I02 — Earnings gaps form and fail. Source: docs/lessons/STOCKS_INTERMEDIATE.md §S-I02. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_S_I02: LessonContent = {
  id: "lesson:earnings-gaps-form-and-fail",
  curriculumId: "S-I02",
  title: "Earnings Gaps Form and Fail",
  track: "stocks",
  pages: [
    [
      "The gap is not the surprise. The gap is the structural",
      "consequence of a market that closes at 16:00 and reopens",
      "at 9:30 with new information. If NGSM reports after the",
      "16:00 close and reprices overnight, the repricing has",
      "nowhere to go until 9:30. At 9:30, accumulated repricing",
      "happens instantly — not as ticks you could exit through,",
      "but as a jump from one price to another with no trades",
      "between them.",
      "",
      "How gaps form:",
      "",
      "Price discovery continues in pre-market (4:00–9:30) on",
      "thin volume. Pre-market prints are visible and often",
      "indicate gap direction, but are not reliable. Thin volume",
      "means large orders move price significantly. Institutional",
      "participants wanting to adjust positions in size often",
      "wait for the regular session open, where deeper liquidity",
      "provides better fills. The 9:30 print is the first truly",
      "liquid price.",
    ],
    [
      "What the gap means for your stop:",
      "",
      "A stop-market order is an instruction to sell when price",
      "reaches or passes a specified level. If price never trades",
      "at your stop — because it gaps from above your stop to",
      "below it — the stop triggers at the market open and fills",
      "at the prevailing market price at that instant, not at",
      "your stated stop level. For a large gap, the difference",
      "can be substantial.",
      "",
      "This is not a broker failure. It is the expected behavior",
      "of a stop order at a gap open. F-04 introduced this in",
      "Foundation Track; S-I02 applies it to earnings context",
      "where gaps are concentrated and predictable in timing.",
    ],
    [
      "Gap-and-hold vs. gap-and-fade:",
      "",
      "After the gap opens, two common structures follow:",
      "",
      "Gap-and-hold: Price opens with a large gap in one",
      "direction and continues in that direction for the first",
      "hour, then stabilizes. The market has absorbed earnings",
      "information and reprices steadily. Buyers or sellers are",
      "committed. This suggests the earnings reaction was",
      "decisive.",
      "",
      "Gap-and-fade: Price opens with a large gap and then",
      "reverses, filling some or all of the gap within the",
      "session. The initial reaction was an overreaction — too",
      "much optimism or panic — and calmer participants bring it",
      "back. This is more common after ambiguous reports.",
    ],
    [
      "Reading gap structure:",
      "",
      "Reading which structure is forming requires watching the",
      "first 20–30 minutes. Volume at the open matters: a gap on",
      "high volume that immediately continues is more likely",
      "gap-and-hold. A gap on declining volume that stalls and",
      "retraces is more likely gap-and-fade. Neither is certain;",
      "both are probabilistic observations from chart structure.",
      "",
      "Policy statement:",
      "",
      "The process requirement from this lesson is simple but",
      "non-negotiable: you should be able to state, in writing,",
      "before any earnings event, whether you will (a) hold",
      "through the report, (b) exit before the close on report",
      "day, or (c) stand aside and trade the reaction on the",
      "next open. That statement is your policy. It exists before",
      "the event, not as post-hoc rationalization.",
    ],
  ],
  processCheck:
    "Do you have a written policy — not a feeling, a written statement — on whether to hold positions through earnings?",
  cta: { kind: "scenario", id: "SCN-002", line: "Practice this now: the earnings gap mechanics scenario." },
};
