/** S-I04 — Dividends. Source: docs/lessons/STOCKS_INTERMEDIATE.md §S-I04. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_S_I04: LessonContent = {
  id: "lesson:dividends",
  curriculumId: "S-I04",
  title: "Dividends",
  track: "stocks",
  pages: [
    [
      "A dividend is a cash payment made by a company to its",
      "shareholders, typically quarterly. When you hold shares of",
      "a dividend-paying company, you receive periodic cash in",
      "proportion to shares held. The mechanics contain several",
      "non-obvious properties every intermediate learner should",
      "understand before treating yield as a criterion.",
      "",
      "How yield is calculated:",
      "",
      "Yield = (Annual dividend per share) / (Current share price)",
      "",
      "NGSM pays $2.40 per year ($0.60 per quarter). At $80,",
      "yield = 3.0%. If NGSM falls to $60, yield = 4.0% — yield",
      "rose because price fell, not because the dividend",
      "increased. A rising yield can signal a falling stock.",
    ],
    [
      "Ex-dividend date mechanics:",
      "",
      "To receive a dividend, you must hold shares before the",
      "ex-dividend date. Buy on or after ex-date: no coming",
      "dividend. On the ex-date, the stock typically opens lower",
      "by approximately the dividend amount — buyers from that",
      "point forward will not receive the payment priced in.",
      "",
      "Worked example: NGSM at $80 the day before ex-date.",
      "Quarterly dividend $0.60. On ex-date morning, NGSM opens",
      "near $79.40. If you held before ex-date, you receive",
      "$0.60 — total value still ~$80.00 (price + cash).",
      "",
      "Buy on ex-date at $79.40 and immediately sell: you will",
      "not receive the dividend. The discount is not free income.",
    ],
    [
      "The dividend capture myth:",
      "",
      "Buying just before ex-date to collect the dividend and",
      "sell is not a reliable profit strategy. In an efficient",
      "market, share price adjusts by the dividend amount on",
      "ex-date. Transaction costs and slippage typically make",
      "dividend capture negative-expectancy.",
      "",
      "Yield vs. growth tradeoff:",
      "",
      "Dividend payers tend to be mature with stable revenues.",
      "Growth companies reinvest earnings. Neither is inherently",
      "better — the choice depends on purpose and time horizon.",
    ],
    [
      "Why yield is not a buy signal:",
      "",
      "High yield can mean a genuinely generous dividend, or a",
      "price that fell sharply while the dividend has not yet",
      "been cut — a \"yield trap.\" The yield number does not tell",
      "you which scenario you are in.",
      "",
      "Before treating yield as positive, ask: is the dividend",
      "sustainable? That requires earnings coverage and free cash",
      "flow trend — not just the current yield figure.",
    ],
  ],
  processCheck:
    "Can you explain why dividend yield alone is not a buy signal — what the yield number does not tell you?",
  cta: { kind: "scenario", id: "SCN-005", line: "Practice this now: passive-fund mechanics and total-return thinking in the index inclusion scenario." },
};
