/** S-I05 — Index rebalancing mechanics. Source: docs/lessons/STOCKS_INTERMEDIATE.md §S-I05. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_S_I05: LessonContent = {
  id: "lesson:index-rebalancing-mechanics",
  curriculumId: "S-I05",
  title: "Index Rebalancing Mechanics",
  track: "stocks",
  pages: [
    [
      "The NMX 100 is a fictional index of 100 stocks. Passive",
      "funds that track the NMX 100 — funds whose stated goal is",
      "to match the index's performance — must hold the index's",
      "components in proportion to index weights. When the index",
      "changes its composition (adds a new name, removes an old",
      "one, or reweights members), the passive funds must trade",
      "to match the new composition. That forced trading is",
      "mechanical: it does not depend on any view of whether the",
      "added stock is cheap or expensive. It happens because the",
      "fund's mandate requires it.",
      "",
      "This mechanic creates a predictable, observable price",
      "pattern around inclusion events — and understanding it is",
      "the foundation for understanding why SCN-005 (NMX 100",
      "inclusion of VLDI) unfolds the way it does.",
    ],
    [
      "Why passive funds must buy at inclusion:",
      "",
      "When VLDI is announced as a new NMX 100 component, every",
      "passive fund tracking NMX 100 must eventually hold VLDI",
      "in proportion to its index weight. The funds do not have a",
      "choice — that is what 'passive' means. They must buy",
      "before or at the moment VLDI becomes officially part of",
      "the index (the effective date). Because funds typically",
      "use the closing price on the effective date as their",
      "benchmark price, they concentrate their buying at the",
      "closing auction on that day.",
      "",
      "The front-run pattern:",
      "",
      "Active traders observe the inclusion announcement. They",
      "know passive funds must buy VLDI before the effective",
      "date. So they buy VLDI in advance — 'front-running' the",
      "anticipated passive demand. This buying begins the moment",
      "the announcement is public and continues through the days",
      "leading up to the effective date.",
    ],
    [
      "This is not illegal or unusual — it is participants acting",
      "on publicly available information about a known future",
      "mechanical event. The result is a predictable price run",
      "from announcement date to effective date as demand",
      "accumulates ahead of the forced buyer.",
      "",
      "The closing auction:",
      "",
      "The closing auction is a special order-matching session in",
      "the final minutes of the trading day (~15:50–16:00). In a",
      "standard session, trades execute continuously. In the",
      "closing auction, orders accumulate and match at a single",
      "clearing price at 16:00 — the official closing price.",
      "",
      "Passive index funds use the closing price as their",
      "benchmark. To minimize tracking error, passive funds buy at",
      "the closing auction on the effective date so their average",
      "cost matches the closing price. The concentration of large",
      "passive fund orders in a short window creates a predictable",
      "volume spike — often 8–12× normal daily volume.",
    ],
    [
      "The auction print and immediate reversion:",
      "",
      "In SCN-005, VLDI's auction print on inclusion day reaches",
      "$37.80. The previous session close was ~$37.20. That $0.60",
      "spike is the passive fund buying executing simultaneously.",
      "Once the auction closes and passive funds have their",
      "required shares, the demand is exhausted. The price reverts",
      "immediately to $37.20 at post-auction open — then fades",
      "over following sessions as early front-runners exit.",
      "",
      "This reversion is not a surprise if you understand the",
      "mechanics. The auction spike was caused entirely by one-",
      "time, finite, mechanical demand. Once that demand is",
      "complete, the only buyers left have a fundamental view of",
      "VLDI as a business — no reason they would pay higher than",
      "before the announcement, since nothing about VLDI's",
      "actual business changed.",
      "",
      "Why late chasing is poor process:",
      "",
      "A trader entering Day 1 post-announcement at $34.00 with a",
      "thesis ('mechanical passive-flow front-run') captures most",
      "of the front-run opportunity while mechanical demand is",
      "building. A trader entering Day 3's high of $36.50,",
      "reasoning 'this will keep going into the auction,' has a",
      "fundamentally different risk profile: less flow remaining,",
      "more price risk, and a timing mismatch. The thesis",
      "conflates observing a mechanical event with having a",
      "risk-defined position in it.",
    ],
  ],
  processCheck:
    "Can you state the difference between 'this stock is being added to an index' (a factual observation) and 'I have a process-correct entry in this stock' (a defined position with a driver label, stop, and favorable risk-to-target)?",
  cta: { kind: "scenario", id: "SCN-005", line: "Practice this now: the NMX 100 inclusion scenario." },
};
