/** S-I03 — Sector rotation. Source: docs/lessons/STOCKS_INTERMEDIATE.md §S-I03. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_S_I03: LessonContent = {
  id: "lesson:sector-rotation",
  curriculumId: "S-I03",
  title: "Sector Rotation",
  track: "stocks",
  pages: [
    [
      "The broad stock market is not one homogeneous price. It",
      "is a collection of sectors — groups of companies with",
      "similar business characteristics — that can behave",
      "differently from each other and from the index average.",
      "",
      "Sector rotation is capital flowing from one group to",
      "another as economic conditions, interest rates, or",
      "sentiment change. Understanding rotation is not about",
      "predicting which sector is next. It is about recognizing",
      "that an individual stock can move opposite to the broad",
      "index — and what looks like an individual thesis can",
      "hide a sector-level flow you are unknowingly caught in.",
    ],
    [
      "Defensive vs. growth rotation:",
      "",
      "In risk-off periods, capital tends toward defensive",
      "sectors — revenues stable regardless of economic",
      "conditions (utilities, staples, healthcare). In risk-on",
      "periods, capital flows toward growth sectors — revenues",
      "that scale with economic growth (technology, discretionary",
      "consumer, financials).",
      "",
      "The NMX 100 includes multiple sectors. When growth sells",
      "off and defensive holds or rallies, the index might",
      "appear flat — losses in growth partially offset by gains",
      "in defensive. A trader holding only growth names has a",
      "very different experience than one holding the full index.",
    ],
    [
      "How rotation appears on a chart:",
      "",
      "Rotation is slow — not an overnight event. Signs include:",
      "",
      "• Relative strength divergence — defensive holds while",
      "  growth underperforms its prior trend.",
      "• Volume flow — heavy volume on defensive names, lighter",
      "  on growth, suggests institutional repositioning.",
      "• Breadth narrowing — fewer names making new highs while",
      "  the index is near its own high.",
      "",
      "The observe-before-act rule: By the time rotation is",
      "visible in price, institutional flow has already",
      "substantially repriced those stocks. Sector context is",
      "backdrop awareness — not an entry signal by itself.",
    ],
    [
      "Worked example:",
      "",
      "NGSM (growth) underperforms the NMX 100 by 12 points over",
      "six weeks. Calder Utilities (CALD, defensive) outperforms",
      "by 8 points. You note \"possible defensive rotation.\"",
      "",
      "Your strategy: swing long with defined stop below support.",
      "CALD pulls back 3% after its run. Entry at support, stop",
      "below, risk 1% of account. Journal driver: \"CALD sector",
      "appears to receive inflows — context, not entry reason.",
      "Entry reason: pullback to defined support with declining",
      "volume on the pullback.\"",
      "",
      "You are not chasing the rotation; you are waiting for a",
      "setup within it.",
    ],
  ],
  processCheck:
    "Are you observing sector rotation and waiting for your setup within it, or entering as soon as you label the rotation?",
  cta: { kind: "scenario", id: "SCN-005", line: "Practice this now: index composition and flow in the VLDI inclusion scenario." },
};
