/** X-B04 — Spreads and cost of trading. Source: docs/lessons/BEGINNER_COMPLETIONS.md §X-B04. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_X_B04: LessonContent = {
  id: "lesson:spreads-cost-of-trading",
  curriculumId: "X-B04",
  title: "Spreads and Cost of Trading",
  track: "forex",
  pages: [
    [
      "When you buy ANDU/HarborUSD, you fill at the ask price.",
      "To close immediately, you fill at the bid — which is",
      "lower than ask by the spread. On a 1.5-pip spread, you",
      "are already 1.5 pips in the red the moment you enter.",
      "Price must move 1.5 pips in your favor before you break",
      "even. This is true before any other analysis matters.",
      "",
      "The spread is an immediate, certain loss. It is not an",
      "abstraction. It reduces your effective risk:reward before",
      "price moves at all.",
    ],
    [
      "Worked example during peak session (1.5-pip spread):",
      "Enter long ANDU/HarborUSD with 2 mini lots.",
      "Spread cost: 1.5 pips × $1.00 × 2 = $3.00",
      "Stop: 30 pips. Target: 60 pips.",
      "Stated R:R: 1:2.",
      "",
      "Break-even move: 1.5 pips (the spread cost).",
      "Actual risk distance: 30 + 1.5 = 31.5 pips",
      "Actual reward distance: 60 − 1.5 = 58.5 pips",
      "Adjusted R:R: 31.5 : 58.5 ≈ 1 : 1.86, not 1 : 2.",
      "",
      "The trade you thought was 1:2 is now 1:1.86 before the",
      "market has moved.",
    ],
    [
      "Now enter off-peak (6-pip spread):",
      "Same position, same risk/reward setup.",
      "Spread cost: 6 pips × $1.00 × 2 = $12.00",
      "Break-even: 6 pips.",
      "Actual risk: 30 + 6 = 36 pips",
      "Actual reward: 60 − 6 = 54 pips",
      "Adjusted R:R: 36 : 54 = 1 : 1.5",
      "",
      "If your edge requires minimum 1:2 R:R, this trade does",
      "not meet your rule, regardless of your analysis. When",
      "spread widens, it is a valid reason to delay entry or",
      "reduce position size to keep total dollar risk constant.",
    ],
    [
      "Critical process: Before every forex entry:",
      "1. State the current spread in pips",
      "2. Multiply by pip value and lot size for dollar cost",
      "3. Add spread cost to your stop distance in pips",
      "4. Recalculate R:R with the adjusted distances",
      "",
      "If adjusted R:R no longer meets your minimum threshold,",
      "you have identified a reason to pass on this entry. This",
      "is not overthinking. This is the discipline that keeps",
      "you from entering trades with false expectations about",
      "their probability.",
    ],
  ],
  processCheck: "State the current ANDU/HarborUSD spread. Without a calculator, what is your adjusted R:R if your stop is 25 pips, target is 50 pips, and you trade 1 mini lot? Does it meet a 1:1.8 minimum?",
  cta: { kind: "scenario", id: "SCN-006", line: "Practice this now: the news-event spread scenario." },
};
