/** X-B03 — Forex session windows. Source: docs/lessons/PILLAR_INTROS.md §X-B03. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_X_B03: LessonContent = {
  id: "lesson:forex-session-windows",
  curriculumId: "X-B03",
  title: "Forex Session Windows",
  track: "forex",
  pages: [
    [
      "Forex runs 24 hours on weekdays because it is a global",
      "network of banks and brokers, not a single exchange.",
      "But '24-hour market' does not mean uniformly active.",
      "Activity concentrates where business hours overlap.",
      "The spread you pay — and how easily large orders fill —",
      "changes dramatically across the trading day.",
      "",
      "The four major sessions:",
      "• Sydney: ~22:00–07:00 UTC. Lowest volume.",
      "• Tokyo: ~00:00–09:00 UTC. Asian pairs most active.",
      "• London: ~08:00–17:00 UTC. Highest single volume.",
      "• New York: ~13:00–22:00 UTC.",
    ],
    [
      "The London/New York overlap (~13:00–17:00 UTC) is peak",
      "institutional activity. Spreads are at their narrowest.",
      "Directional moves most frequently occur here.",
      "",
      "Outside the overlap, the market thins. A 1.5-pip spread",
      "during London/New York may widen to 4–8 pips at midnight",
      "UTC. That widening is a direct cost: your risk:reward",
      "calculation must use the actual spread when you enter,",
      "not the tight spread from peak hours.",
      "",
      "Your highest-liquidity window for trading your pair is",
      "the overlap. Entering outside costs more in spread and",
      "may produce fills that deviate more from your target.",
    ],
    [
      "Weekend exposure: Forex closes ~22:00 UTC Friday and",
      "reopens ~22:00 UTC Sunday. Any position held through the",
      "weekend experiences two days of potential news events",
      "with no market to manage them. The gap at Sunday open",
      "can be sharp — you could be forced to take a fill far",
      "from where you expected.",
      "",
      "Key discipline: Know the specific time window — in your",
      "local timezone — when your target forex pair has its",
      "highest liquidity, lowest spread, and therefore lowest",
      "entry cost. This is part of knowing your instrument, not",
      "optional optimization.",
    ],
  ],
  processCheck: "In your local timezone, what are the start and end times of the London/New York overlap? Can you identify the time when your target pair has the tightest spread?",
  cta: { kind: "scenario", id: "SCN-003", line: "Practice this now: the London open sweep scenario." },
};
