/** X-I01 — Session open liquidity sweeps. Source: docs/lessons/FOREX_INTERMEDIATE.md §X-I01. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_X_I01: LessonContent = {
  id: "lesson:session-open-sweeps",
  curriculumId: "X-I01",
  title: "Session Open Sweeps",
  track: "forex",
  pages: [
    [
      "The London open is the highest-volume single-session",
      "event in the forex day. Institutional order flow at a",
      "session open is not directional like a trade entry. Large",
      "participants fill orders across both sides of the book,",
      "probing for liquidity.",
      "",
      "Stop orders from the prior session's range sit in",
      "predictable locations: just below recent swing lows for",
      "longs, just above recent swing highs for shorts. When",
      "large buy or sell orders need liquidity, stop-triggered",
      "orders provide it. The result: a sharp spike beyond the",
      "prior range, followed by reversal once stops are absorbed.",
    ],
    [
      "Example on ANDU/HarborUSD:",
      "",
      "Prior session low: 1.2380",
      "London open: Price dips sharply to 1.2363 (clearing",
      "stops placed just below 1.2380), then recovers above",
      "1.2390 within twenty minutes.",
      "",
      "A trader's stop at 1.2375 was stopped out before the",
      "anticipated move ever developed. The position thesis may",
      "have been correct. The stop placement did not account for",
      "the mechanical spike of the sweep.",
      "",
      "This is not market manipulation. It is mechanical: large",
      "orders find the stops they need to fill.",
    ],
    [
      "The practical takeaway is geometric:",
      "",
      "If the London open routinely spikes X pips beyond prior",
      "lows/highs, a stop placed at exactly the prior extreme is",
      "inside the typical sweep distance. A stop placed beyond",
      "the realistic sweep range survives the spike.",
      "",
      "But a wider stop requires a smaller position to maintain",
      "your 1% dollar-risk rule. There is no free option.",
      "You either accept a wider stop with smaller size, or",
      "accept that a tight stop will be triggered regularly at",
      "the open.",
    ],
    [
      "Build this habit: Before the London open, note the prior",
      "session's high, low, and mid-range. These are not",
      "prediction targets. They are reference points for where",
      "stop clusters sit mechanically.",
      "",
      "Knowing the map tells you which areas carry mechanical",
      "significance. It does not tell you what price will do.",
      "But it tells you where the vulnerability exists and how",
      "much clearance your stop needs to survive the initial",
      "spike. This discipline is the foundation of placing stops",
      "that remain intact through high-volume session opens.",
    ],
  ],
  processCheck: "Identify the prior session's high and low on your chart. At what distance beyond those extremes would a sweep typically spike? What stop placement would survive a typical sweep for a long position?",
  cta: { kind: "scenario", id: "SCN-003", line: "Practice this now: the London open liquidity sweep scenario." },
};
