/** X-I04 — Why retail forex loses. Source: docs/lessons/FOREX_INTERMEDIATE.md §X-I04. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_X_I04: LessonContent = {
  id: "lesson:why-retail-forex-loses",
  curriculumId: "X-I04",
  title: "Why Retail Forex Loses: The Numbers",
  track: "forex",
  pages: [
    [
      "F-09 introduced the broad picture: fees, over-leverage,",
      "no edge, emotional override. This lesson narrows to forex",
      "specifically — forex carries the worst aggregate retail",
      "loss statistics of any market in this curriculum, and the",
      "reasons are specific enough that \"trading is hard\" does",
      "not do the work.",
      "",
      "The disclosure numbers:",
      "",
      "Regulated brokers in the EU, UK, Australia, and elsewhere",
      "must publish the percentage of retail accounts that lose",
      "money. Disclosed figures typically cluster between 67% and",
      "82%, with some above. These are mandatory public",
      "disclosures — not cherry-picked pessimism.",
    ],
    [
      "What the numbers mean structurally:",
      "",
      "• Losing-account percentage is not evenly distributed —",
      "  accounts closing within 90 days inflate the rate.",
      "• Disclosures cover active retail accounts over a trailing",
      "  period — a starting point for honest accounting, not a",
      "  complete picture.",
      "• Broker revenue is partially from spread and partly from",
      "  market-maker structure. This is disclosed as \"we may be",
      "  your counterparty\" — a structural conflict of interest,",
      "  not proof of manipulation.",
    ],
    [
      "Structural disadvantages beyond leverage:",
      "",
      "1. Information asymmetry — institutional participants have",
      "   bank-level order flow data retail traders do not. Stop",
      "   cluster locations are statistically knowable to them.",
      "",
      "2. Cost disadvantage — institutions trade interbank spreads",
      "   a fraction of retail. A 1.5 pip retail spread is many",
      "   multiples of institutional cost. Small per trade;",
      "   compounds over hundreds of trades.",
      "",
      "3. Leverage availability — retail maximums are multiples of",
      "   what professionals use. High leverage generates broker",
      "   revenue when accounts blow up quickly.",
    ],
    [
      "What this lesson is not saying:",
      "",
      "It is not saying retail forex is irrational or that no",
      "participant can develop durable process. Some do. The",
      "lesson says: the baseline is adversarial in specific,",
      "structural ways. Treating those disadvantages as solvable",
      "by chart skill alone is an error.",
      "",
      "The response is honest accounting — understand your cost",
      "structure, leverage constraints, and information",
      "environment before you set a lot size. Read the broker",
      "risk disclosure you accepted; know the disclosed loss rate.",
    ],
  ],
  processCheck:
    "Have you read the broker risk disclosure you accepted — not skimmed — and do you know the disclosed loss rate for retail accounts?",
  cta: { kind: "scenario", id: "SCN-003", line: "Practice this now: London open mechanics and stop vulnerability on ANDU." },
};
