/** X-I03 — The carry concept. Source: docs/lessons/FOREX_INTERMEDIATE.md §X-I03. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_X_I03: LessonContent = {
  id: "lesson:carry-concept",
  curriculumId: "X-I03",
  title: "The Carry Concept",
  track: "forex",
  pages: [
    [
      "Every currency belongs to an economy with a central bank",
      "and an interest rate. When you hold a forex position",
      "overnight, you hold one currency (the base you bought) and",
      "borrow another (the quote you sold). If the currency you",
      "hold pays a higher rate than the currency you borrowed,",
      "the net differential is credited to your account. This is",
      "carry — and it sounds like free money until you account",
      "for when it is not.",
    ],
    [
      "The mechanics:",
      "",
      "In the TradeGame sandbox, ANDU carries a higher notional",
      "rate than HarborUSD. Holding long ANDU/HarborUSD means",
      "you hold the higher-rate currency and are short the lower.",
      "The daily rollover credit (swap) is applied at session",
      "close. On a micro lot it may be fractions of a pip per day.",
      "Carry matters over weeks and months when price also moves",
      "in your favor — a second return layered on appreciation.",
    ],
    [
      "When carry works vs. bleeds:",
      "",
      "Positive carry performs best when price trends in the",
      "direction of the carry — the higher-yielding currency",
      "also strengthening. You collect the differential while",
      "price appreciation compounds return.",
      "",
      "In a ranging market, price goes nowhere while swap credits",
      "accumulate slowly — carry barely covers spread cost. In a",
      "sharp reversal, weeks of carry can be erased in days.",
      "",
      "The leverage interaction: Carry per lot per day is small.",
      "The only way to make carry \"feel\" large is large lot",
      "sizes — which means large leverage. Over-leverage in a",
      "reversing environment produces losses that dwarf carry.",
    ],
    [
      "Worked example — 3 mini lots ANDU/HarborUSD, 10 days:",
      "",
      "Daily swap credit: $0.42 per mini lot. Total carry:",
      "3 × $0.42 × 10 = $12.60.",
      "",
      "ANDU/HarborUSD drops 45 pips. Pip value for 3 mini lots:",
      "$3.00/pip. Price loss: 45 × $3.00 = $135.00.",
      "",
      "Net: $12.60 − $135.00 = −$122.40. Carry paid back about",
      "9% of the price loss — indistinguishable from noise.",
      "",
      "Position sizing (F-03) still governs: stop distance",
      "determines size, not the carry credit you hope to collect.",
    ],
  ],
  processCheck:
    "Can you name — right now — the condition that would turn a positive-carry position into a net loser?",
  cta: { kind: "scenario", id: "SCN-006", line: "Practice this now: ANDU session dynamics and event risk in the employment report scenario." },
};
