/** X-I02 — High-impact news events. Source: docs/lessons/FOREX_INTERMEDIATE.md §X-I02. */
import type { LessonContent } from "../../../lessons/types.js";

export const LESSON_X_I02: LessonContent = {
  id: "lesson:high-impact-news-events",
  curriculumId: "X-I02",
  title: "High-Impact News Events",
  track: "forex",
  pages: [
    [
      "Forex markets respond to scheduled economic releases",
      "with speed and violence unlike any routine event in the",
      "trading week. In the minutes before a high-impact release",
      "— a labor report, central bank rate decision, inflation",
      "print — market makers widen spreads substantially.",
      "",
      "Liquidity providers pull quotes because they do not want",
      "to be filled at a stale price the moment data crosses.",
      "ANDU/HarborUSD spread widens from 1.5 pips to 8–15 pips",
      "in the two minutes before release. You are not paying",
      "worse because conditions are worse for you. You are",
      "paying because the market refuses to take risk during",
      "maximum uncertainty.",
    ],
    [
      "The spike-and-reversal pattern:",
      "",
      "The release hits. Algorithmic readers process the number",
      "in milliseconds and fire orders before any human can",
      "react. Price moves 40, 60, or 100+ pips in seconds.",
      "Then, frequently, it partially or fully reverses as",
      "secondary interpretation — nuance algorithms missed —",
      "flows in over the next minutes.",
      "",
      "Example: ANDU labor report better than expected. ANDU/",
      "HarborUSD spikes upward 60 pips, then retraces 35 pips",
      "as traders reassess forward rate implications. Both spike",
      "and retrace happen within five minutes.",
    ],
    [
      "Why your stop cannot help you:",
      "",
      "A stop-market order exits at the next available price",
      "after your stop level is touched. During a news spike,",
      "the 'next available price' can be 20–40 pips beyond your",
      "stop level because the bid-ask has evaporated.",
      "",
      "Worked example: Long ANDU at 1.3250, stop at 1.3200.",
      "Plan: 50-pip risk. Account: $5,000 (1% = $50 risk).",
      "Release: Price drops 80 pips in three seconds.",
      "Stop fills at 1.3168 — 32 pips of slippage beyond the",
      "stop level. Actual loss: 82 pips × $1.00 = $82.",
      "You planned for $50. Slippage that no placement prevents.",
    ],
    [
      "The policy question:",
      "",
      "Many structured traders maintain a written rule: flat",
      "before [high-impact event]. Some define 'flat' as zero",
      "positions; others close pairs directly affected while",
      "keeping unaffected exposure.",
      "",
      "The curriculum does not prescribe a choice. Your policy",
      "belongs in your trading plan. What the curriculum insists",
      "on: the policy is written before the release, not decided",
      "in the moment while watching the spread widen to 12 pips.",
      "",
      "Spreads change dynamically after you are already in. If",
      "your plan does not address how you handle that, the event",
      "makes the decision for you.",
    ],
  ],
  processCheck: "Before the next high-impact news release on ANDU, write your policy: will you hold or exit? If you hold, what is the maximum slippage you will accept? If you exit, at what spread level will you close?",
  cta: { kind: "scenario", id: "SCN-006", line: "Practice this now: the labor report news event scenario." },
};
